"""Application database services.

The module keeps its historical name so existing imports and local test
fixtures remain compatible.  ``DATABASE_URL`` selects PostgreSQL (including a
Supabase connection string); without it the app continues to use SQLite.
"""

from __future__ import annotations

import atexit
import json
import re
import sqlite3
import threading
import time
from contextlib import contextmanager
from pathlib import Path
from typing import Any, Iterator
from urllib.parse import urlsplit

from core.config.settings import settings


SCHEMA_MIGRATIONS_TABLE = "app_schema_migrations"
POSTGRES_MIGRATION_LOCK_ID = 4_139_188_001
POSTGRES_SCHEMES = {"postgres", "postgresql"}
SCHEMA_NAME_PATTERN = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


class DatabaseJSONMixin:
    @staticmethod
    def dumps(value: Any) -> str:
        return json.dumps(value)

    @staticmethod
    def loads(value: str | None, fallback: Any = None) -> Any:
        if not value:
            return fallback
        try:
            return json.loads(value)
        except (json.JSONDecodeError, TypeError):
            return fallback


def _schema_statements(backend: str) -> list[str]:
    auto_id = (
        "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
        if backend == "postgresql"
        else "INTEGER PRIMARY KEY AUTOINCREMENT"
    )
    return [
        f"""
        CREATE TABLE IF NOT EXISTS memory_messages (
          id {auto_id},
          user_id TEXT NOT NULL DEFAULT 'local',
          session_id TEXT NOT NULL,
          role TEXT NOT NULL,
          content TEXT NOT NULL,
          timestamp TEXT NOT NULL
        )
        """,
        "CREATE INDEX IF NOT EXISTS idx_memory_session ON memory_messages(session_id, id)",
        """
        CREATE TABLE IF NOT EXISTS memory_facts (
          id TEXT PRIMARY KEY,
          user_id TEXT NOT NULL DEFAULT 'local',
          content TEXT NOT NULL,
          timestamp TEXT NOT NULL
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS model_settings (
          task TEXT PRIMARY KEY,
          model TEXT NOT NULL
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS user_model_settings (
          user_id TEXT NOT NULL,
          task TEXT NOT NULL,
          model TEXT NOT NULL,
          PRIMARY KEY (user_id, task)
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS chat_conversations (
          id TEXT PRIMARY KEY,
          user_id TEXT NOT NULL DEFAULT 'local',
          title TEXT NOT NULL,
          created_at DOUBLE PRECISION NOT NULL,
          updated_at DOUBLE PRECISION NOT NULL
        )
        """,
        f"""
        CREATE TABLE IF NOT EXISTS chat_messages (
          id {auto_id},
          conversation_id TEXT NOT NULL,
          role TEXT NOT NULL,
          content TEXT NOT NULL,
          route TEXT,
          model TEXT,
          sources_json TEXT,
          chart_json TEXT,
          sql_text TEXT,
          rows_json TEXT,
          created_at DOUBLE PRECISION NOT NULL,
          FOREIGN KEY(conversation_id) REFERENCES chat_conversations(id) ON DELETE CASCADE
        )
        """,
        "CREATE INDEX IF NOT EXISTS idx_chat_messages_conversation ON chat_messages(conversation_id, id)",
        """
        CREATE TABLE IF NOT EXISTS auth_users (
          id TEXT PRIMARY KEY,
          email TEXT NOT NULL UNIQUE,
          password_hash TEXT NOT NULL,
          email_verified INTEGER NOT NULL DEFAULT 0,
          created_at DOUBLE PRECISION NOT NULL,
          updated_at DOUBLE PRECISION NOT NULL
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS auth_email_tokens (
          token_hash TEXT PRIMARY KEY,
          user_id TEXT NOT NULL,
          expires_at DOUBLE PRECISION NOT NULL,
          used_at DOUBLE PRECISION,
          created_at DOUBLE PRECISION NOT NULL,
          FOREIGN KEY(user_id) REFERENCES auth_users(id) ON DELETE CASCADE
        )
        """,
        "CREATE INDEX IF NOT EXISTS idx_auth_email_tokens_user ON auth_email_tokens(user_id)",
        """
        CREATE TABLE IF NOT EXISTS auth_sessions (
          token_hash TEXT PRIMARY KEY,
          user_id TEXT NOT NULL,
          created_at DOUBLE PRECISION NOT NULL,
          expires_at DOUBLE PRECISION NOT NULL,
          last_seen_at DOUBLE PRECISION NOT NULL,
          FOREIGN KEY(user_id) REFERENCES auth_users(id) ON DELETE CASCADE
        )
        """,
        "CREATE INDEX IF NOT EXISTS idx_auth_sessions_user ON auth_sessions(user_id)",
        """
        CREATE TABLE IF NOT EXISTS career_preferences (
          user_id TEXT PRIMARY KEY,
          preferences_json TEXT NOT NULL,
          updated_at DOUBLE PRECISION NOT NULL
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS career_profile (
          user_id TEXT PRIMARY KEY,
          cv_text TEXT NOT NULL,
          updated_at DOUBLE PRECISION NOT NULL
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS career_jobs (
          id TEXT PRIMARY KEY,
          user_id TEXT NOT NULL DEFAULT 'local',
          title TEXT NOT NULL,
          company TEXT,
          location TEXT,
          url TEXT,
          description TEXT NOT NULL,
          source TEXT NOT NULL,
          status TEXT NOT NULL,
          fit_score INTEGER,
          decision TEXT,
          analysis_json TEXT,
          applied_at DOUBLE PRECISION,
          created_at DOUBLE PRECISION NOT NULL,
          updated_at DOUBLE PRECISION NOT NULL
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS career_score_batches (
          id TEXT PRIMARY KEY,
          user_id TEXT NOT NULL DEFAULT 'local',
          status TEXT NOT NULL,
          cv_text TEXT NOT NULL,
          total INTEGER NOT NULL DEFAULT 0,
          completed INTEGER NOT NULL DEFAULT 0,
          failed INTEGER NOT NULL DEFAULT 0,
          created_at DOUBLE PRECISION NOT NULL,
          updated_at DOUBLE PRECISION NOT NULL
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS career_score_tasks (
          batch_id TEXT NOT NULL,
          job_id TEXT NOT NULL,
          status TEXT NOT NULL,
          error TEXT,
          created_at DOUBLE PRECISION NOT NULL,
          updated_at DOUBLE PRECISION NOT NULL,
          PRIMARY KEY (batch_id, job_id),
          FOREIGN KEY(batch_id) REFERENCES career_score_batches(id) ON DELETE CASCADE,
          FOREIGN KEY(job_id) REFERENCES career_jobs(id) ON DELETE CASCADE
        )
        """,
        "CREATE INDEX IF NOT EXISTS idx_career_score_tasks_status ON career_score_tasks(status, created_at)",
        f"""
        CREATE TABLE IF NOT EXISTS usage_events (
          id {auto_id},
          user_id TEXT NOT NULL,
          action TEXT NOT NULL,
          created_at DOUBLE PRECISION NOT NULL
        )
        """,
        "CREATE INDEX IF NOT EXISTS idx_usage_events_user_action_time ON usage_events(user_id, action, created_at)",
    ]


def _scope_index_statements() -> list[str]:
    return [
        "CREATE INDEX IF NOT EXISTS idx_memory_user_session ON memory_messages(user_id, session_id, id)",
        "CREATE INDEX IF NOT EXISTS idx_memory_facts_user ON memory_facts(user_id, timestamp)",
        "CREATE INDEX IF NOT EXISTS idx_chat_conversations_user ON chat_conversations(user_id, updated_at)",
        "CREATE INDEX IF NOT EXISTS idx_career_jobs_user_updated ON career_jobs(user_id, updated_at DESC)",
    ]


def _performance_index_statements() -> list[str]:
    return [
        "CREATE INDEX IF NOT EXISTS idx_career_score_tasks_job "
        "ON career_score_tasks(job_id)",
    ]


class SQLiteService(DatabaseJSONMixin):
    backend = "sqlite"

    def __init__(self, path: str | None = None):
        self.path = Path(path or settings.SQLITE_PATH)
        self.path.parent.mkdir(parents=True, exist_ok=True)
        self._lock = threading.Lock()
        self._init()

    def connect(self):
        conn = sqlite3.connect(self.path, check_same_thread=False, timeout=10)
        conn.row_factory = sqlite3.Row
        conn.execute("PRAGMA foreign_keys = ON")
        conn.execute("PRAGMA busy_timeout = 10000")
        conn.execute("PRAGMA synchronous = NORMAL")
        return conn

    def execute(self, sql: str, params: tuple = ()):
        with self._lock, self.connect() as conn:
            conn.execute(sql, params)
            conn.commit()

    def query(self, sql: str, params: tuple = ()) -> list[dict[str, Any]]:
        with self.connect() as conn:
            rows = conn.execute(sql, params).fetchall()
            return [dict(row) for row in rows]

    def query_one(self, sql: str, params: tuple = ()) -> dict[str, Any] | None:
        with self.connect() as conn:
            row = conn.execute(sql, params).fetchone()
            return dict(row) if row else None

    def execute_many(self, statements: list[tuple[str, tuple]]):
        with self._lock, self.connect() as conn:
            for sql, params in statements:
                conn.execute(sql, params)
            conn.commit()

    def _init(self):
        with self.connect() as conn:
            conn.execute("PRAGMA journal_mode = WAL")
        self.execute(
            f"""
            CREATE TABLE IF NOT EXISTS {SCHEMA_MIGRATIONS_TABLE} (
              version INTEGER PRIMARY KEY,
              name TEXT NOT NULL,
              applied_at DOUBLE PRECISION NOT NULL
            )
            """
        )
        applied = {
            int(row["version"])
            for row in self.query(f"SELECT version FROM {SCHEMA_MIGRATIONS_TABLE}")
        }
        if 1 not in applied:
            statements = [(sql, ()) for sql in _schema_statements(self.backend)]
            statements.append((
                f"INSERT INTO {SCHEMA_MIGRATIONS_TABLE} (version, name, applied_at) VALUES (?, ?, ?)",
                (1, "initial_schema", time.time()),
            ))
            self.execute_many(statements)
        if 2 not in applied:
            self._migrate_user_scopes()
            self.execute(
                f"INSERT INTO {SCHEMA_MIGRATIONS_TABLE} (version, name, applied_at) VALUES (?, ?, ?)",
                (2, "user_scopes", time.time()),
            )
        if 3 not in applied:
            self.execute_many([(sql, ()) for sql in _performance_index_statements()])
            self.execute(
                f"INSERT INTO {SCHEMA_MIGRATIONS_TABLE} (version, name, applied_at) VALUES (?, ?, ?)",
                (3, "foreign_key_indexes", time.time()),
            )

    def _has_column(self, table: str, column: str) -> bool:
        rows = self.query(f"PRAGMA table_info({table})")
        return any(row["name"] == column for row in rows)

    def _add_column_if_missing(self, table: str, column: str, ddl: str):
        if not self._has_column(table, column):
            self.execute(f"ALTER TABLE {table} ADD COLUMN {column} {ddl}")

    def _migrate_user_scopes(self):
        self._migrate_career_singleton_table(
            "career_preferences", "preferences_json TEXT NOT NULL", "preferences_json", "{}"
        )
        self._migrate_career_singleton_table(
            "career_profile", "cv_text TEXT NOT NULL", "cv_text", ""
        )
        self._add_column_if_missing("memory_messages", "user_id", "TEXT NOT NULL DEFAULT 'local'")
        self._add_column_if_missing("memory_facts", "user_id", "TEXT NOT NULL DEFAULT 'local'")
        self._add_column_if_missing("chat_conversations", "user_id", "TEXT NOT NULL DEFAULT 'local'")
        self._add_column_if_missing("career_jobs", "user_id", "TEXT NOT NULL DEFAULT 'local'")
        self._add_column_if_missing("career_jobs", "applied_at", "DOUBLE PRECISION")
        self._add_column_if_missing("career_score_batches", "user_id", "TEXT NOT NULL DEFAULT 'local'")
        self.execute_many([(sql, ()) for sql in _scope_index_statements()])

    def _migrate_career_singleton_table(
        self,
        table: str,
        value_ddl: str,
        value_column: str,
        fallback: str,
    ):
        columns = [row["name"] for row in self.query(f"PRAGMA table_info({table})")]
        if not columns or "id" not in columns:
            return

        row = self.query_one(f"SELECT {value_column}, updated_at FROM {table} WHERE id = 1")
        value = row[value_column] if row else fallback
        updated_at = row["updated_at"] if row else 0
        self.execute_many([
            (f"DROP TABLE {table}", ()),
            (
                f"""
                CREATE TABLE {table} (
                  user_id TEXT PRIMARY KEY,
                  {value_ddl},
                  updated_at DOUBLE PRECISION NOT NULL
                )
                """,
                (),
            ),
            (
                f"INSERT INTO {table} (user_id, {value_column}, updated_at) VALUES (?, ?, ?)",
                ("local", value, updated_at),
            ),
        ])


class PostgreSQLService(DatabaseJSONMixin):
    backend = "postgresql"

    def __init__(
        self,
        database_url: str,
        *,
        pool: Any | None = None,
        initialize: bool = True,
        schema: str | None = None,
    ):
        self.database_url = (database_url or "").strip()
        parsed = urlsplit(self.database_url)
        if parsed.scheme.lower() not in POSTGRES_SCHEMES or not parsed.hostname:
            raise ValueError("DATABASE_URL must be a PostgreSQL connection URL")

        self.schema = (schema or settings.DATABASE_SCHEMA).strip()
        if not SCHEMA_NAME_PATTERN.fullmatch(self.schema):
            raise ValueError("DATABASE_SCHEMA must be a simple PostgreSQL identifier")

        self._owns_pool = pool is None
        self._closed = False
        self._pool = pool or self._create_pool()
        if self._owns_pool:
            self._pool.wait(timeout=settings.DATABASE_CONNECT_TIMEOUT_SECONDS)
            atexit.register(self.close)
        if initialize:
            self._init()

    def _create_pool(self):
        try:
            from psycopg.rows import dict_row
            from psycopg_pool import ConnectionPool
        except ImportError as exc:  # pragma: no cover - exercised in deployment packaging
            raise RuntimeError(
                "PostgreSQL support requires the psycopg and psycopg-pool packages"
            ) from exc

        connection_kwargs: dict[str, Any] = {
            "application_name": "ai-platform",
            "connect_timeout": settings.DATABASE_CONNECT_TIMEOUT_SECONDS,
            "prepare_threshold": None,
            "row_factory": dict_row,
        }
        if settings.DATABASE_SSLMODE:
            connection_kwargs["sslmode"] = settings.DATABASE_SSLMODE
        return ConnectionPool(
            conninfo=self.database_url,
            min_size=settings.DATABASE_POOL_MIN_SIZE,
            max_size=settings.DATABASE_POOL_MAX_SIZE,
            timeout=settings.DATABASE_CONNECT_TIMEOUT_SECONDS,
            kwargs=connection_kwargs,
            check=ConnectionPool.check_connection,
            open=True,
        )

    @contextmanager
    def connect(self) -> Iterator[Any]:
        with self._pool.connection() as conn:
            # SET LOCAL is transaction-scoped, so it is safe with both a local
            # client pool and Supabase's transaction-mode pooler.
            conn.execute(f'SET LOCAL search_path TO "{self.schema}"')
            yield conn

    def close(self):
        if self._owns_pool and self._pool is not None and not self._closed:
            self._pool.close()
            self._closed = True

    def execute(self, sql: str, params: tuple = ()):
        with self.connect() as conn:
            conn.execute(self._convert_placeholders(sql), params)

    def query(self, sql: str, params: tuple = ()) -> list[dict[str, Any]]:
        with self.connect() as conn:
            rows = conn.execute(self._convert_placeholders(sql), params).fetchall()
            return [dict(row) for row in rows]

    def query_one(self, sql: str, params: tuple = ()) -> dict[str, Any] | None:
        with self.connect() as conn:
            row = conn.execute(self._convert_placeholders(sql), params).fetchone()
            return dict(row) if row else None

    def execute_many(self, statements: list[tuple[str, tuple]]):
        with self.connect() as conn:
            for sql, params in statements:
                conn.execute(self._convert_placeholders(sql), params)

    def _init(self):
        with self.connect() as conn:
            conn.execute("SELECT pg_advisory_xact_lock(%s)", (POSTGRES_MIGRATION_LOCK_ID,))
            conn.execute(f'CREATE SCHEMA IF NOT EXISTS "{self.schema}"')
            conn.execute(
                f"""
                CREATE TABLE IF NOT EXISTS {SCHEMA_MIGRATIONS_TABLE} (
                  version INTEGER PRIMARY KEY,
                  name TEXT NOT NULL,
                  applied_at DOUBLE PRECISION NOT NULL
                )
                """
            )
            applied = {
                int(row["version"])
                for row in conn.execute(
                    f"SELECT version FROM {SCHEMA_MIGRATIONS_TABLE}"
                ).fetchall()
            }
            if 1 not in applied:
                for statement in _schema_statements(self.backend):
                    conn.execute(statement)
                conn.execute(
                    f"INSERT INTO {SCHEMA_MIGRATIONS_TABLE} "
                    "(version, name, applied_at) VALUES (%s, %s, %s)",
                    (1, "initial_schema", time.time()),
                )
            if 2 not in applied:
                for statement in self._postgres_scope_migration_statements():
                    conn.execute(statement)
                conn.execute(
                    f"INSERT INTO {SCHEMA_MIGRATIONS_TABLE} "
                    "(version, name, applied_at) VALUES (%s, %s, %s)",
                    (2, "user_scopes", time.time()),
                )
            if 3 not in applied:
                for statement in _performance_index_statements():
                    conn.execute(statement)
                conn.execute(
                    f"INSERT INTO {SCHEMA_MIGRATIONS_TABLE} "
                    "(version, name, applied_at) VALUES (%s, %s, %s)",
                    (3, "foreign_key_indexes", time.time()),
                )

    @staticmethod
    def _postgres_scope_migration_statements() -> list[str]:
        return [
            "ALTER TABLE memory_messages ADD COLUMN IF NOT EXISTS user_id TEXT NOT NULL DEFAULT 'local'",
            "ALTER TABLE memory_facts ADD COLUMN IF NOT EXISTS user_id TEXT NOT NULL DEFAULT 'local'",
            "ALTER TABLE chat_conversations ADD COLUMN IF NOT EXISTS user_id TEXT NOT NULL DEFAULT 'local'",
            "ALTER TABLE career_jobs ADD COLUMN IF NOT EXISTS user_id TEXT NOT NULL DEFAULT 'local'",
            "ALTER TABLE career_jobs ADD COLUMN IF NOT EXISTS applied_at DOUBLE PRECISION",
            "ALTER TABLE career_score_batches ADD COLUMN IF NOT EXISTS user_id TEXT NOT NULL DEFAULT 'local'",
            *_scope_index_statements(),
        ]

    @staticmethod
    def _convert_placeholders(sql: str) -> str:
        """Convert DB-API qmark placeholders without touching SQL literals.

        Existing application services intentionally keep the SQLite-style
        ``?`` API. Psycopg uses ``%s``; this small lexer handles quoted text,
        identifiers, comments, and PostgreSQL dollar-quoted strings.
        """

        output: list[str] = []
        index = 0
        state = "normal"
        dollar_tag = ""
        while index < len(sql):
            char = sql[index]
            next_char = sql[index + 1] if index + 1 < len(sql) else ""

            if state == "normal":
                if char == "'":
                    state = "single"
                elif char == '"':
                    state = "double"
                elif char == "-" and next_char == "-":
                    output.extend((char, next_char))
                    index += 2
                    state = "line_comment"
                    continue
                elif char == "/" and next_char == "*":
                    output.extend((char, next_char))
                    index += 2
                    state = "block_comment"
                    continue
                elif char == "$":
                    match = re.match(r"\$[A-Za-z_][A-Za-z0-9_]*\$|\$\$", sql[index:])
                    if match:
                        dollar_tag = match.group(0)
                        output.append(dollar_tag)
                        index += len(dollar_tag)
                        state = "dollar"
                        continue
                elif char == "?":
                    output.append("%s")
                    index += 1
                    continue
            elif state == "single":
                if char == "'":
                    if next_char == "'":
                        output.extend((char, next_char))
                        index += 2
                        continue
                    state = "normal"
            elif state == "double":
                if char == '"':
                    if next_char == '"':
                        output.extend((char, next_char))
                        index += 2
                        continue
                    state = "normal"
            elif state == "line_comment":
                if char in "\r\n":
                    state = "normal"
            elif state == "block_comment":
                if char == "*" and next_char == "/":
                    output.extend((char, next_char))
                    index += 2
                    state = "normal"
                    continue
            elif state == "dollar" and sql.startswith(dollar_tag, index):
                output.append(dollar_tag)
                index += len(dollar_tag)
                state = "normal"
                continue

            output.append(char)
            index += 1
        return "".join(output)


PostgresService = PostgreSQLService


def create_database_service(
    database_url: str | None = None,
    *,
    sqlite_path: str | None = None,
):
    resolved_url = settings.DATABASE_URL if database_url is None else database_url
    if not (resolved_url or "").strip():
        return SQLiteService(sqlite_path)
    return PostgreSQLService(resolved_url)


db = create_database_service()
