CREATE SCHEMA IF NOT EXISTS app_private;

COMMENT ON SCHEMA app_private IS
  'Private relational storage for the AI Platform backend; not exposed through the Supabase Data API.';

REVOKE ALL ON SCHEMA app_private FROM PUBLIC;
REVOKE ALL ON SCHEMA app_private FROM anon, authenticated;

CREATE TABLE IF NOT EXISTS app_private.app_schema_migrations (
  version INTEGER PRIMARY KEY,
  name TEXT NOT NULL,
  applied_at DOUBLE PRECISION NOT NULL
);

CREATE TABLE IF NOT EXISTS app_private.memory_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL DEFAULT 'local',
  session_id TEXT NOT NULL,
  role TEXT NOT NULL,
  content TEXT NOT NULL,
  timestamp TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_memory_session
  ON app_private.memory_messages(session_id, id);

CREATE INDEX IF NOT EXISTS idx_memory_user_session
  ON app_private.memory_messages(user_id, session_id, id);

CREATE TABLE IF NOT EXISTS app_private.memory_facts (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL DEFAULT 'local',
  content TEXT NOT NULL,
  timestamp TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_memory_facts_user
  ON app_private.memory_facts(user_id, timestamp);

CREATE TABLE IF NOT EXISTS app_private.model_settings (
  task TEXT PRIMARY KEY,
  model TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS app_private.user_model_settings (
  user_id TEXT NOT NULL,
  task TEXT NOT NULL,
  model TEXT NOT NULL,
  PRIMARY KEY (user_id, task)
);

CREATE TABLE IF NOT EXISTS app_private.chat_conversations (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL DEFAULT 'local',
  title TEXT NOT NULL,
  created_at DOUBLE PRECISION NOT NULL,
  updated_at DOUBLE PRECISION NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_chat_conversations_user
  ON app_private.chat_conversations(user_id, updated_at);

CREATE TABLE IF NOT EXISTS app_private.chat_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversation_id TEXT NOT NULL,
  role TEXT NOT NULL,
  content TEXT NOT NULL,
  route TEXT,
  model TEXT,
  sources_json TEXT,
  chart_json TEXT,
  sql_text TEXT,
  rows_json TEXT,
  created_at DOUBLE PRECISION NOT NULL,
  FOREIGN KEY (conversation_id)
    REFERENCES app_private.chat_conversations(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_chat_messages_conversation
  ON app_private.chat_messages(conversation_id, id);

CREATE TABLE IF NOT EXISTS app_private.auth_users (
  id TEXT PRIMARY KEY,
  email TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  email_verified INTEGER NOT NULL DEFAULT 0,
  created_at DOUBLE PRECISION NOT NULL,
  updated_at DOUBLE PRECISION NOT NULL
);

CREATE TABLE IF NOT EXISTS app_private.auth_email_tokens (
  token_hash TEXT PRIMARY KEY,
  user_id TEXT NOT NULL,
  expires_at DOUBLE PRECISION NOT NULL,
  used_at DOUBLE PRECISION,
  created_at DOUBLE PRECISION NOT NULL,
  FOREIGN KEY (user_id)
    REFERENCES app_private.auth_users(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_auth_email_tokens_user
  ON app_private.auth_email_tokens(user_id);

CREATE TABLE IF NOT EXISTS app_private.auth_sessions (
  token_hash TEXT PRIMARY KEY,
  user_id TEXT NOT NULL,
  created_at DOUBLE PRECISION NOT NULL,
  expires_at DOUBLE PRECISION NOT NULL,
  last_seen_at DOUBLE PRECISION NOT NULL,
  FOREIGN KEY (user_id)
    REFERENCES app_private.auth_users(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_auth_sessions_user
  ON app_private.auth_sessions(user_id);

CREATE TABLE IF NOT EXISTS app_private.career_preferences (
  user_id TEXT PRIMARY KEY,
  preferences_json TEXT NOT NULL,
  updated_at DOUBLE PRECISION NOT NULL
);

CREATE TABLE IF NOT EXISTS app_private.career_profile (
  user_id TEXT PRIMARY KEY,
  cv_text TEXT NOT NULL,
  updated_at DOUBLE PRECISION NOT NULL
);

CREATE TABLE IF NOT EXISTS app_private.career_jobs (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL DEFAULT 'local',
  title TEXT NOT NULL,
  company TEXT,
  location TEXT,
  url TEXT,
  description TEXT NOT NULL,
  source TEXT NOT NULL,
  status TEXT NOT NULL,
  fit_score INTEGER,
  decision TEXT,
  analysis_json TEXT,
  applied_at DOUBLE PRECISION,
  created_at DOUBLE PRECISION NOT NULL,
  updated_at DOUBLE PRECISION NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_career_jobs_user_updated
  ON app_private.career_jobs(user_id, updated_at DESC);

CREATE TABLE IF NOT EXISTS app_private.career_score_batches (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL DEFAULT 'local',
  status TEXT NOT NULL,
  cv_text TEXT NOT NULL,
  total INTEGER NOT NULL DEFAULT 0,
  completed INTEGER NOT NULL DEFAULT 0,
  failed INTEGER NOT NULL DEFAULT 0,
  created_at DOUBLE PRECISION NOT NULL,
  updated_at DOUBLE PRECISION NOT NULL
);

CREATE TABLE IF NOT EXISTS app_private.career_score_tasks (
  batch_id TEXT NOT NULL,
  job_id TEXT NOT NULL,
  status TEXT NOT NULL,
  error TEXT,
  created_at DOUBLE PRECISION NOT NULL,
  updated_at DOUBLE PRECISION NOT NULL,
  PRIMARY KEY (batch_id, job_id),
  FOREIGN KEY (batch_id)
    REFERENCES app_private.career_score_batches(id) ON DELETE CASCADE,
  FOREIGN KEY (job_id)
    REFERENCES app_private.career_jobs(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_career_score_tasks_status
  ON app_private.career_score_tasks(status, created_at);

CREATE TABLE IF NOT EXISTS app_private.usage_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL,
  action TEXT NOT NULL,
  created_at DOUBLE PRECISION NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_usage_events_user_action_time
  ON app_private.usage_events(user_id, action, created_at);

INSERT INTO app_private.app_schema_migrations (version, name, applied_at)
VALUES
  (1, 'initial_schema', EXTRACT(EPOCH FROM NOW())),
  (2, 'user_scopes', EXTRACT(EPOCH FROM NOW()))
ON CONFLICT (version) DO NOTHING;
